# Generated by Django 4.1.3 on 2022-11-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yodepApi', '0002_testimony_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='files/project')),
                ('pdescription', models.TextField()),
            ],
        ),
    ]
