# Generated by Django 4.1.3 on 2022-11-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yodepApi', '0005_gallary'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsTitle', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='files/news')),
                ('body', models.TextField()),
            ],
        ),
    ]
