# Generated by Django 4.1.3 on 2022-11-24 09:38

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('yodepApi', '0006_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now=True)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
