# Generated by Django 4.1.3 on 2022-12-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yodepApi', '0012_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=250)),
                ('position_summary', models.CharField(max_length=300)),
                ('duties', models.CharField(max_length=500)),
                ('education', models.CharField(max_length=300)),
                ('method_of_application', models.CharField(max_length=300)),
                ('closing_date', models.DateField()),
            ],
        ),
    ]
